CodersCrew/coderscamp

- Procfile
- app.json
- package.json
- packages/api/package.json
- packages/api/src/main.ts
> ci: setup CD to create multiple environments (#7)

- .gitignore
- README.md
- packages/api/.env
- packages/api/.env.example
- packages/api/package.json
- packages/api/src/app.module.ts
- packages/api/src/common/env.ts
- packages/api/src/main.ts
- packages/api/tsconfig.json
- yarn.lock
> refactor(api): Add api env variables validation (#26)

- packages/ui/src/components/IconButton/IconButton.stories.tsx
- packages/ui/src/components/IconButton/IconButton.test.tsx
- packages/ui/src/components/IconButton/IconButton.tsx
- packages/ui/src/components/IconButton/index.ts
> feat: Create icon button (#13)

- packages/ui/src/components/Input/Input.stories.tsx
- packages/ui/src/components/Input/Input.test.tsx
- packages/ui/src/components/Input/Input.tsx
- packages/ui/src/components/Input/index.ts
- packages/ui/src/theme/overwrites/components/index.ts
- packages/ui/src/theme/overwrites/components/input.ts
> feat(ui): Create Input component (#31)

- packages/docs/src/best-practices.md
Some suggestions related to our code review workflow. Feel free to disagree with certain points, propose additions and modifications.
> docs: Create code review guidelines (#52)

- packages/ui/src/components/Input/Input.test.tsx
> fix(ui): Fix Input component tests (#60)

- .github/workflows/create-issue-branch.yml
> ci: add "Create Issue Branch" workflow (#69)

- .github/renovate.json
- .github/workflows/pull-request.yml
- packages/docs/src/workflow.md
> ci(core): Add branch name checking to the workflow (#80)

- packages/ui/src/components/CheckboxGroup/CheckboxGroup.test.tsx
- packages/ui/src/components/CheckboxGroup/CheckboxGroup.tsx
- packages/ui/src/components/CheckboxGroup/index.ts
> feat(ui): Create CheckboxGroup Component (#36)

- packages/ui/src/components/MaterialsCard/MaterialsCard.stories.tsx
- packages/ui/src/components/MaterialsCard/MaterialsCard.test.tsx
- packages/ui/src/components/MaterialsCard/MaterialsCard.tsx
- packages/ui/src/components/MaterialsCard/index.ts
> feat(ui): Create MaterialsCard Component (#61)

- packages/ui/src/components/BenefitCard/BenefitCard.stories.tsx
- packages/ui/src/components/BenefitCard/BenefitCard.test.tsx
- packages/ui/src/components/BenefitCard/BenefitCard.tsx
- packages/ui/src/components/BenefitCard/index.ts
> feat(ui): create BenefitCard component (#110)

- packages/ui/package.json
- packages/ui/src/components/Checkbox/Checkbox.tsx
- packages/ui/src/components/CheckboxGroup/CheckboxGroup.tsx
- packages/ui/src/components/FormControl/FieldContext.test.tsx
- packages/ui/src/components/FormControl/FieldContext.tsx
- packages/ui/src/components/FormControl/FormControl.stories.tsx
- packages/ui/src/components/FormControl/FormControl.test.tsx
- packages/ui/src/components/FormControl/FormControl.tsx
- packages/ui/src/components/FormControl/index.ts
- packages/ui/src/components/HelperText/HelperText.tsx
- packages/ui/src/components/Input/Input.tsx
- packages/ui/src/components/Label/Label.tsx
- packages/ui/src/components/NumberInput/NumberInput.tsx
- packages/ui/src/components/Radio/Radio.tsx
- packages/ui/src/components/RadioGroup/RadioGroup.tsx
- packages/ui/src/components/Typography/Typography.tsx
- packages/ui/src/theme/overwrites/components/checkbox.ts
- packages/ui/src/theme/overwrites/components/radio.ts
- yarn.lock
> feat(ui): create FormControl component (#129)

- packages/panel/src/GoToFormPage/GoToFormPage.tsx
- packages/panel/src/SignUpPageForCandidates/SignUpPageForCandidates.tsx
- packages/ui/src/components/MaterialsCard/MaterialsCard.tsx
- packages/ui/src/components/Typography/Typography.tsx
> fix(ui): fix Typography component props type (#130)

- packages/ui/src/components/TimelineItem/TimelineItem.stories.tsx
- packages/ui/src/components/TimelineItem/TimelineItem.test.tsx
- packages/ui/src/components/TimelineItem/TimelineItem.tsx
- packages/ui/src/components/TimelineItem/index.ts
> feat(ui): create timeline item component (#111)

- packages/ui/src/components/SimpleGrid.tsx
- packages/website/src/components/BigNumbers/BigNumbers.tsx
- packages/website/src/components/BigNumbers/Statistic.tsx
- packages/website/src/components/BigNumbers/StatsWithTitle.tsx
- packages/website/src/components/BigNumbers/index.tsx
- packages/website/src/pages/index.tsx
> feat(website): create big numbers section (#93)

- packages/ui/src/components/CheckboxGroup/CheckboxGroup.tsx
- packages/ui/src/components/FormField/FormField.stories.tsx
- packages/ui/src/components/FormField/FormField.test.tsx
- packages/ui/src/components/FormField/FormField.tsx
- packages/ui/src/components/FormField/index.ts
- packages/ui/src/components/Input/Input.tsx
- packages/ui/src/components/NumberInput/NumberInput.tsx
- packages/ui/src/components/RadioGroup/RadioGroup.tsx
- packages/ui/src/components/Textarea/Textarea.tsx
> feat(ui): create FormField component (#137)

- packages/ui/src/components/Requirement/Requirement.stories.tsx
- packages/ui/src/components/Requirement/Requirement.test.tsx
- packages/ui/src/components/Requirement/Requirement.tsx
- packages/ui/src/components/Requirement/index.ts
- packages/website/src/components/MentorRequirements.tsx
- packages/website/src/pages/mentor.tsx
> feat(website): Create mentor requirements section (#105)

- packages/website/src/components/MentorPerspective.tsx
- packages/website/src/components/Navbar/BaseNavbar.tsx
- packages/website/src/pages/mentor.tsx
- packages/website/src/pages/mentorzy.tsx
> feat(website): create MentorPerspective section (#103) 

- packages/ui/src/components/SliderSteps/SliderSteps.test.tsx
- packages/ui/src/components/SliderSteps/SliderSteps.tsx
- packages/ui/src/hooks/useMediaQuery.ts
- packages/ui/src/theme/overwrites/index.ts
- packages/website/next-env.d.ts
- packages/website/package.json
- packages/website/src/components/Projects/ProjectCard.tsx
- packages/website/src/components/Projects/Projects.data.ts
- packages/website/src/components/Projects/Projects.tsx
- packages/website/src/components/Projects/ProjectsCarousel.tsx
- packages/website/src/components/Projects/index.ts
- packages/website/src/hooks/useRerender.ts
- packages/website/src/pages/_app.tsx
- packages/website/src/pages/index.tsx
- yarn.lock
> feat(website): create Projects section (#98)

- packages/ui/src/components/CourseProgressCard/CourseProgressCard.mock.ts
- packages/ui/src/components/CourseProgressCard/CourseProgressCard.stories.tsx
- packages/ui/src/components/CourseProgressCard/CourseProgressCard.test.tsx
- packages/ui/src/components/CourseProgressCard/CourseProgressCard.tsx
- packages/ui/src/components/CourseProgressCard/index.ts
> feat(ui): create CourseProgressComponent (#64)

- packages/website/src/components/Testimonials/TestimonialCard.tsx
- packages/website/src/components/Testimonials/Testimonials.data.ts
- packages/website/src/components/Testimonials/Testimonials.tsx
- packages/website/src/components/Testimonials/TestimonialsCarousel.tsx
- packages/website/src/components/Testimonials/index.ts
- packages/website/src/pages/index.tsx
> feat(website): create Testimonials section (#96)

- packages/website/src/components/AboutMentor/AboutMentor.tsx
- packages/website/src/components/AboutMentor/MentorProfits.data.ts
- packages/website/src/components/AboutMentor/ProfitDescription.tsx
- packages/website/src/components/AboutMentor/index.tsx
- packages/website/src/components/MentorPerspective.tsx
- packages/website/src/pages/mentor.tsx
> feat(website): create about mentor section (#102)

- .github/workflows/code-check.yml
- packages/api/.env.example
- packages/api/package.json
- packages/api/prisma/migrations/20210817181119_learning_materials/migration.sql
- packages/api/prisma/schema.prisma
- packages/api/src/app.module.ts
- packages/api/src/common/env.ts
- packages/api/src/learning-materials/adapters/users.adapter.ts
- packages/api/src/learning-materials/learning-materials.controller.ts
- packages/api/src/learning-materials/learning-materials.module.ts
- packages/api/src/learning-materials/learning-materials.repository.ts
- packages/api/src/learning-materials/learning-materials.service.ts
- packages/api/src/learning-materials/learning-materials.utils.ts
- packages/api/src/learning-materials/ports/users.port.ts
- packages/api/src/users/users.module.ts
- packages/shared/src/models/learning-material.ts
- yarn.lock
Closes #68 
Co-authored-by: Mateusz Nowak <kontakt.mateusznowak@gmail.com>
> feat(api): create checklist generation endpoint (#68)

- packages/api/src/auth/github/github.module.ts
- packages/api/src/auth/github/github.service.spec.ts
- packages/api/src/auth/github/github.service.ts
- packages/api/src/learning-materials/adapters/users.adapter.ts
- packages/api/src/learning-materials/learning-materials.module.ts
- packages/api/src/users/users.controller.ts
- packages/api/src/users/users.module.ts
- packages/api/src/users/users.repository.ts
- packages/api/src/users/users.service.ts
A small change to increase the cohesion of our backend codebase
> refactor(api): separate UsersService and UsersRepository

- packages/website/src/components/Testimonials/AboutTestimonials/AboutTestimonialCard.tsx
- packages/website/src/components/Testimonials/AboutTestimonials/AboutTestimonials.tsx
- packages/website/src/components/Testimonials/MentorTestimonials/MentorTestimonialCard.tsx
- packages/website/src/components/Testimonials/MentorTestimonials/MentorTestimonials.tsx
- packages/website/src/components/Testimonials/Testimonials.data.ts
- packages/website/src/components/Testimonials/Testimonials.tsx
- packages/website/src/components/Testimonials/TestimonialsCarousel.tsx
- packages/website/src/components/Testimonials/index.ts
- packages/website/src/pages/index.tsx
- packages/website/src/pages/mentor.tsx
> feat(website): create MentorTestimonials section (#106)

- packages/ui/src/components/Question/Question.tsx
- packages/ui/src/components/Question/QuestionsAccordion.tsx
- packages/website/src/components/BigNumbers/BigNumbers.tsx
- packages/website/src/components/Faq/Faq.data.tsx
- packages/website/src/components/Faq/Faq.tsx
- packages/website/src/components/Faq/index.ts
- packages/website/src/components/InternalLink.tsx
- packages/website/src/constants.ts
- packages/website/src/plurals.ts
> feat(website): add FAQ page content (#175)

- packages/website/src/components/Hero.tsx
> fix: text consistency on buttons (#207)

- packages/website/src/components/RecruitmentModal/RecruitmentModal.tsx
- packages/website/src/components/RecruitmentModal/RecruitmentModalForm.tsx
> fix(website): add cancel icon to modals

- packages/website/src/components/About.tsx
> fix: change text in section "Czym jest CodersCamp" (#253)

- packages/api/src/app.module.ts
- packages/api/src/module/shared/commands/request-email-conformation.ts
- packages/api/src/module/shared/events/email-confirmation-was-requested.domain-event.ts
- packages/api/src/module/write/email-confirmation/application/request-email-confirmation-application-command-handler.ts
- packages/api/src/module/write/email-confirmation/domain/events.ts
- packages/api/src/module/write/email-confirmation/domain/requestEmailConfirmation.spec.ts
- packages/api/src/module/write/email-confirmation/domain/requestEmailConfirmation.ts
- packages/api/src/module/write/email-confirmation/email-confirmation.spec.ts
- packages/api/src/module/write/email-confirmation/email-confirmation.test-module.ts
- packages/api/src/module/write/email-confirmation/email-confirmation.write-module.ts
> feat(api): [write | emailConfirmation] create slice RequestEmailConfirmation -> EmailConfirmationWasRequested #279

- packages/api/src/module/shared/events/email-confirmation-was-approved.domain.event.ts
> feat(api): [emailConfirmation] create event type EmailConfirmationWasApproved #285

- .vscode/api/email-confirmation.http
- .vscode/api/learning-materials.http
- packages/api/src/module/write/email-confirmation/email-confirmation.write-module.ts
- packages/api/src/module/write/email-confirmation/presentation/rest/email-confirmation.rest-controller.ts
- packages/shared/src/models/email-confirmation.ts
> feat(api): [write | EmailConfirmation] REST API endpoint for RequestEmailConfirmation #280

- README.md
> docs(core): add codecov badge (#266)

- .github/workflows/code-check.yml
- packages/api/.env.example
- packages/api/src/shared/env.ts
> feat(api): create CURRENT_COURSE_ID env variable (#325)

- packages/ui/src/components/IconButton/IconButton.tsx
- packages/ui/src/components/SliderSteps/SliderStep.tsx
- packages/ui/src/components/SliderSteps/SliderSteps.test.tsx
- packages/ui/src/components/SliderSteps/SliderSteps.tsx
- packages/ui/src/hooks/useCurrentBreakpoint.ts
- packages/ui/src/types.ts
- packages/website/src/components/Testimonials/TestimonialsCarousel.tsx
> fix(website): bigger dots in horizontal nav (#206)

- .github/workflows/code-check.yml
- packages/api/.env.test
- packages/api/jest-setup.ts
> feat(api): dotenv config for tests (#348)

- packages/api/src/module/automation/send-email-when-learning-materials-url-was-generated/learning-materials-url-was-generated-event-handler.service.ts
- packages/api/src/module/automation/when-user-registration-was-started-then-request-email-confirmation/user-registration-was-started.event-handler.ts
- packages/api/src/module/read/course-progress/course-progress.read-module.ts
- packages/api/src/module/read/learning-materials/learning-materials.read-module.ts
- packages/api/src/module/write/email-confirmation/application/approve-email-confirmation-application-command-handler.ts
- packages/api/src/module/write/email-confirmation/application/request-email-confirmation-application-command-handler.ts
- packages/docs/src/workspaces/api.md
* add ICommandHandler interfaces where missing
> fix(api): change OnModuleInit to OnApplicationBootstrap for subscriptions #352

- packages/api/src/module/automation/when-email-confirmation-was-approved-then-complete-user-registration/email-confirmation-was-approved-event-handler.service.ts
- packages/api/src/module/automation/when-email-confirmation-was-approved-then-complete-user-registration/when-email-confirmation-was-approved-then-complete-user-registration.spec.ts
- packages/api/src/module/automation/when-user-registration-was-started-then-request-email-confirmation/user-registration-was-started.event-handler.service.ts
- packages/api/src/module/read/course-progress/course-progress.read-module.ts
- packages/api/src/module/read/learning-materials/learning-materials.read-module.ts
- packages/api/src/module/write/register-course-user/register-course-user.test-module.ts
- packages/api/src/module/write/register-course-user/register-course-user.write-module.spec.ts
- packages/api/src/module/write/shared/application/events-subscription/events-subscription.ts
Try to find the cause: 
https://github.com/CodersCrew/coderscamp/issues/368
> fix(api): add retry for upsert fail in EventsSubscription #368

- .vscode/launch.json
- .vscode/settings.json
- packages/api/src/module/automation/when-email-confirmation-was-approved-then-complete-user-registration/when-email-confirmation-was-approved-then-complete-user-registration.spec.ts
- packages/api/src/module/automation/when-email-confirmation-was-approved-then-complete-user-registration/when-email-confirmation-was-approved-then-complete-user-registration.test-module.ts
> test(core): add settings for "Jest" extension for vsCode (#407)
